### ISSUE TITLE
Attempts to start shards before knowing how many shards to start when shardCount is auto

### ISSUE THREAD

**Issue by PikaDude** [discordware/eris-sharder#44]
If the shardCount is set to 0, then the following if statement results to true allowing the code to run which gets a recommended amount of shards to run. (`src/sharding/clustermanager:193`)
```javascript
if (this.shardCount === 0) {
    this.eris.getBotGateway().then(result => {
        this.calculateShards(result.shards).then(shards => {
            this.shardCount = shards;
            this.lastShardID = this.shardCount - 1;
        });
    });
}

logger.info("Cluster Manager", `Starting ${this.shardCount} shards in ${this.clusterCount} clusters`);

let embed = {
    title: `Starting ${this.shardCount} shards in ${this.clusterCount} clusters`
}

this.sendWebhook("cluster", embed);

master.setupMaster({
    silent: true
});

// Fork workers.
this.start(0);
```
However, the code inside of the if statement is asynchronous, which means that the code after the if statement will most likely run before the code inside of the if statement finishes, resulting in the program effectively hanging and returning a message similar to `Cluster Manager | Starting 0 shards in 12 clusters` since shardCount is still set to 0. While this may not happen in environments with ultra-fast internet, the chances of this happening are still very likely.

**Comment by AnotherGenZ** [comment]
Should be fixed in 1.8.3, lemme know if this problem continues to occur though.
