### ISSUE TITLE
Shard disconect 

### ISSUE THREAD

**Issue by TutoRapide** [discordware/eris-sharder#55]
Hello,
I've got a problem with Is Shards. All they do is disconnect. 
Error: **Connection reset by peer**

Operating system : **debian 9**,
Processors: **x64 Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz,**
Core: **6**,
Nodejs: **12.16.1**,
Eris-sharder: **1.9.0**,

Bot:
Guild: 3,749
shards: 4
Cluster: 1

![2020-03-10_09h15_20](https://user-images.githubusercontent.com/37155363/76292643-e2acdd80-62af-11ea-92c7-dd98ecca68ca.png)

**Comment by worldeva** [comment]
If I remember correctly, Connection reset by peer is generally caused if you have a synchronous operation causing you to not reply to discord (timeout), or if your internet is garbage (seeing as its specific shards, probably not). It's pretty normal, nothing to be worried about, and Eris auto-reconnects. I just throw a try/catch around my bot#connect(), and ignore it. [Here's discord's response codes](https://discord.com/developers/docs/topics/opcodes-and-status-codes#http).
